export const glossary = [
  { term: 'Ask', category: 'Precio', short: 'Precio al que normalmente se ejecuta una compra.', detail: 'En MT5 verás Bid y Ask. La diferencia entre ambos es el spread. En una compra, el precio relevante de entrada suele ser Ask.' },
  { term: 'Balance', category: 'Cuenta', short: 'Dinero de la cuenta sin contar el resultado flotante de posiciones abiertas.', detail: 'Cambia cuando se realizan resultados, depósitos, retiros u otros ajustes. No es lo mismo que patrimonio/equity.' },
  { term: 'Bid', category: 'Precio', short: 'Precio al que normalmente se ejecuta una venta.', detail: 'En una venta, el precio relevante de entrada suele ser Bid. El gráfico puede mostrar un precio distinto según la configuración.' },
  { term: 'Breakout', category: 'Movimiento', short: 'Ruptura de una zona que el precio venía respetando.', detail: 'Una ruptura no garantiza continuación. Puede fallar, volver a la zona o convertirse en un falso breakout.' },
  { term: 'Buy / Compra', category: 'Orden', short: 'Posición que busca beneficiarse de un movimiento alcista posterior.', detail: 'Una compra gana valor si el precio sube lo suficiente desde la entrada, descontando spread, comisiones y otros costes aplicables.' },
  { term: 'Buy Limit', category: 'Orden pendiente', short: 'Compra pendiente colocada por debajo del precio actual.', detail: 'Se usa cuando el plan contempla que el precio retroceda a una zona inferior antes de intentar continuar al alza.' },
  { term: 'Buy Stop', category: 'Orden pendiente', short: 'Compra pendiente colocada por encima del precio actual.', detail: 'Se usa cuando el plan depende de que el precio alcance o supere un nivel superior antes de entrar.' },
  { term: 'Candle / Vela', category: 'Gráfico', short: 'Representa apertura, cierre, máximo y mínimo de un periodo.', detail: 'El cuerpo muestra la distancia entre apertura y cierre; las mechas muestran extremos alcanzados durante el periodo.' },
  { term: 'Comisión', category: 'Coste', short: 'Cargo que puede aplicar según el instrumento y tipo de cuenta.', detail: 'No todos los instrumentos/cuentas cobran igual. Debe considerarse junto al spread y posibles swaps.' },
  { term: 'Drawdown', category: 'Riesgo', short: 'Caída desde un máximo de capital hasta un mínimo posterior.', detail: 'Sirve para entender la severidad de una racha negativa y si el tamaño de las posiciones está siendo sostenible.' },
  { term: 'Equity / Patrimonio', category: 'Cuenta', short: 'Balance más o menos el resultado flotante de posiciones abiertas.', detail: 'Puede cambiar segundo a segundo mientras haya operaciones abiertas.' },
  { term: 'Falso breakout', category: 'Movimiento', short: 'Ruptura que no logra sostenerse y vuelve al rango o zona previa.', detail: 'Es una razón para no asumir que toda ruptura es confirmación. El contexto y la gestión del riesgo importan.' },
  { term: 'Gap', category: 'Movimiento', short: 'Salto entre precios donde hay poca o ninguna negociación visible.', detail: 'Puede aparecer tras cierres de mercado o eventos. En mercados 24/5 suele verse con más claridad alrededor del fin de semana.' },
  { term: 'Lote / Volumen', category: 'Riesgo', short: 'Tamaño de la posición.', detail: 'Aumentar volumen aumenta tanto la ganancia potencial como la pérdida potencial. Su significado monetario depende del instrumento.' },
  { term: 'Margen', category: 'Cuenta', short: 'Capital reservado para mantener posiciones apalancadas.', detail: 'No es una comisión. Es una parte de los fondos que queda comprometida mientras la posición está abierta.' },
  { term: 'Margen libre', category: 'Cuenta', short: 'Patrimonio disponible después del margen usado.', detail: 'Indica cuánto colchón queda para soportar fluctuaciones o abrir nuevas posiciones.' },
  { term: 'Market Order', category: 'Orden', short: 'Orden que intenta ejecutarse al mejor precio disponible en ese momento.', detail: 'Prioriza ejecución, no un precio exacto. En movimientos rápidos el precio final puede diferir del visto al enviar la orden.' },
  { term: 'M1 / M5 / M15 / H1…', category: 'Gráfico', short: 'Temporalidades: cada vela representa ese intervalo.', detail: 'M5 significa que cada vela resume 5 minutos; H1, una hora; D1, un día. Cambiar timeframe cambia el nivel de detalle, no el activo.' },
  { term: 'Pullback', category: 'Movimiento', short: 'Retroceso temporal dentro de un movimiento mayor.', detail: 'Puede ser normal dentro de una tendencia. No todo retroceso implica que la tendencia terminó.' },
  { term: 'Rango', category: 'Movimiento', short: 'Mercado que oscila entre una zona superior e inferior sin dirección clara.', detail: 'Dentro del rango, los extremos suelen ser más relevantes que el centro; una ruptura puede iniciar una nueva fase.' },
  { term: 'R:R / Riesgo-beneficio', category: 'Riesgo', short: 'Comparación entre lo que se arriesga y lo que se busca ganar.', detail: 'Por ejemplo, 1:2 significa que el objetivo teórico está al doble de distancia que la invalidación. No dice nada sobre la probabilidad de éxito.' },
  { term: 'Sell / Venta', category: 'Orden', short: 'Posición que busca beneficiarse de un movimiento bajista posterior.', detail: 'Una venta gana valor si el precio cae lo suficiente desde la entrada, considerando los costes aplicables.' },
  { term: 'Sell Limit', category: 'Orden pendiente', short: 'Venta pendiente colocada por encima del precio actual.', detail: 'Se usa cuando el plan espera un rebote hacia una zona superior antes de un posible movimiento bajista.' },
  { term: 'Sell Stop', category: 'Orden pendiente', short: 'Venta pendiente colocada por debajo del precio actual.', detail: 'Se usa cuando el plan depende de que el precio alcance o rompa un nivel inferior antes de entrar.' },
  { term: 'Slippage / Deslizamiento', category: 'Ejecución', short: 'Diferencia entre el precio esperado y el precio de ejecución.', detail: 'Puede ocurrir por volatilidad, liquidez o velocidad del mercado. Un SL/TP tampoco garantiza siempre un precio exacto.' },
  { term: 'Spread', category: 'Coste', short: 'Diferencia entre Bid y Ask.', detail: 'Es uno de los costes más visibles al entrar. Puede ampliarse durante baja liquidez o alta volatilidad.' },
  { term: 'Stop Loss (SL)', category: 'Riesgo', short: 'Nivel para cerrar automáticamente una operación si se mueve en contra.', detail: 'Sirve para definir invalidación y limitar exposición. En movimientos bruscos puede ejecutarse al siguiente precio disponible.' },
  { term: 'Soporte', category: 'Análisis', short: 'Zona donde históricamente apareció interés comprador o frenó una caída.', detail: 'Debe tratarse como zona, no como una línea mágica. Puede romperse o cambiar de función.' },
  { term: 'Resistencia', category: 'Análisis', short: 'Zona donde históricamente apareció oferta o frenó una subida.', detail: 'Al igual que soporte, es una referencia contextual y puede romperse.' },
  { term: 'Swap', category: 'Coste', short: 'Ajuste de financiación que puede aplicarse al mantener posiciones entre sesiones.', detail: 'Depende del instrumento, dirección de la posición, condiciones de cuenta y calendario.' },
  { term: 'Take Profit (TP)', category: 'Gestión', short: 'Nivel para cerrar automáticamente una operación con beneficio esperado.', detail: 'No convierte la operación en segura. En volatilidad extrema, la ejecución puede diferir del nivel indicado.' },
  { term: 'Tendencia', category: 'Movimiento', short: 'Secuencia persistente de máximos y mínimos que muestra dirección dominante.', detail: 'Puede ser alcista, bajista o perder estructura y pasar a rango. El timeframe cambia la tendencia que observas.' },
  { term: 'Volatilidad', category: 'Mercado', short: 'Velocidad y amplitud con la que se mueve el precio.', detail: 'Mayor volatilidad puede ampliar recorridos, spread y deslizamiento, por lo que el tamaño y los stops requieren más atención.' },
]

export const modules = [
  { id: 'terminal', title: '1. Conoce el terminal', subtitle: 'Qué estás mirando en MT5', icon: '▦' },
  { id: 'chart', title: '2. Lee el gráfico', subtitle: 'Velas, temporalidades y estructura', icon: '⌁' },
  { id: 'movements', title: '3. Movimientos comunes', subtitle: 'Tendencias, rangos, rupturas y trampas', icon: '↗' },
  { id: 'setups', title: '4. Jugadas / setups', subtitle: 'Cómo estructurar una idea sin usar señales', icon: '◎' },
  { id: 'orders', title: '5. Abrir una operación', subtitle: 'BUY, SELL, volumen, SL y TP', icon: '＋' },
  { id: 'manage', title: '6. Gestionar y cerrar', subtitle: 'Qué hacer mientras la posición está abierta', icon: '⇄' },
  { id: 'risk', title: '7. Riesgo y disciplina', subtitle: 'Sobrevivir antes que acertar', icon: '◇' },
  { id: 'glossary', title: '8. Glosario', subtitle: 'Términos clave en un solo lugar', icon: 'A' },
  { id: 'library', title: '9. Biblioteca base', subtitle: 'Libros y documentación de referencia', icon: '▤' },
]

export const movements = [
  {
    name: 'Tendencia alcista',
    badge: 'Estructura',
    description: 'El precio encadena impulsos y retrocesos manteniendo máximos y mínimos progresivamente más altos.',
    watch: '¿Los retrocesos respetan zonas previas? ¿La estructura sigue intacta en el timeframe que estás operando?',
    trap: 'Comprar solo porque “sube” después de un movimiento extendido, sin saber dónde quedaría invalidada la idea.',
    points: [[8,82],[18,66],[27,72],[38,50],[47,57],[60,33],[70,42],[82,18],[94,25]],
  },
  {
    name: 'Tendencia bajista',
    badge: 'Estructura',
    description: 'El precio forma máximos y mínimos descendentes; los rebotes no consiguen recuperar la estructura previa.',
    watch: 'Diferencia un rebote normal de un cambio real de estructura. Mira dónde queda el último máximo relevante.',
    trap: 'Vender tarde tras una caída vertical solo por miedo a “perderse” el movimiento.',
    points: [[8,18],[18,34],[28,27],[39,49],[49,42],[60,66],[70,58],[82,80],[94,73]],
  },
  {
    name: 'Rango / lateralización',
    badge: 'Equilibrio',
    description: 'El precio oscila entre una zona superior y una inferior sin construir una tendencia limpia.',
    watch: 'Identifica los extremos del rango y evita interpretar el ruido del centro como una señal fuerte.',
    trap: 'Entrar repetidamente en medio del rango, donde la relación entre invalidación y objetivo suele ser menos clara.',
    points: [[8,49],[18,32],[29,63],[40,37],[51,60],[62,35],[73,61],[84,39],[94,52]],
  },
  {
    name: 'Breakout + retest',
    badge: 'Transición',
    description: 'El precio rompe una zona relevante y después vuelve a comprobarla desde el otro lado antes de continuar o fallar.',
    watch: 'La clave no es “rompió = entro”, sino si la ruptura se sostiene, cómo reacciona al retest y dónde se invalida.',
    trap: 'Perseguir la primera vela grande de ruptura sin espacio para un stop razonable.',
    points: [[8,70],[22,67],[36,68],[48,66],[57,30],[67,18],[73,43],[82,35],[94,15]],
  },
  {
    name: 'Falso breakout',
    badge: 'Trampa',
    description: 'El precio atraviesa una zona, atrae entradas de continuación y luego regresa rápidamente al área previa.',
    watch: 'Observa cierre de velas, aceptación fuera de la zona y qué ocurre cuando el precio vuelve al nivel roto.',
    trap: 'Usar una mecha aislada como confirmación de ruptura o reversión sin contexto.',
    points: [[8,62],[21,60],[35,59],[48,61],[58,27],[65,48],[73,65],[84,67],[94,61]],
  },
  {
    name: 'Spike de volatilidad',
    badge: 'Riesgo',
    description: 'Movimiento muy rápido y amplio, frecuente alrededor de noticias, aperturas o cambios bruscos de liquidez.',
    watch: 'Spread, slippage, tamaño de posición y velocidad. El precio mostrado no siempre será el precio final de ejecución.',
    trap: 'Aumentar volumen por emoción justo cuando el comportamiento del mercado se vuelve menos predecible.',
    points: [[8,53],[20,50],[32,55],[45,52],[53,10],[57,88],[62,32],[70,58],[82,46],[94,50]],
  },
]

export const setups = [
  {
    title: 'Ruptura + retest',
    context: 'Una zona relevante deja de contener al precio y la ruptura se sostiene.',
    plan: 'Esperar retorno a la zona, observar reacción y definir la invalidación antes de decidir si existe una entrada.',
    invalidation: 'El precio recupera con claridad el rango anterior o rompe la estructura que justificaba la idea.',
    mistake: 'Confundir cualquier toque con confirmación y colocar el stop exactamente en el nivel obvio sin margen contextual.',
    level: 'Intermedio',
  },
  {
    title: 'Pullback en tendencia',
    context: 'Existe una tendencia identificable y el precio retrocede hacia una zona de estructura previa.',
    plan: 'Separar impulso de retroceso, comprobar que la estructura principal sigue válida y buscar una entrada con invalidación definida.',
    invalidation: 'El retroceso deja de ser retroceso y rompe la estructura que sostenía la tendencia.',
    mistake: 'Entrar en cada retroceso sin filtrar tendencia, volatilidad o ubicación dentro del recorrido.',
    level: 'Básico',
  },
  {
    title: 'Rechazo en extremo de rango',
    context: 'El mercado lleva tiempo oscilando entre zonas relativamente claras.',
    plan: 'Evaluar el comportamiento cerca del extremo, no en el centro. El objetivo educativo es entender dónde la idea deja de tener sentido.',
    invalidation: 'El precio acepta fuera del rango y transforma el escenario en una ruptura.',
    mistake: 'Seguir tratando el mercado como rango después de que la estructura cambió.',
    level: 'Básico',
  },
  {
    title: 'Cambio de estructura',
    context: 'Una tendencia pierde su secuencia de máximos/mínimos y aparece una ruptura relevante en sentido contrario.',
    plan: 'No intentar adivinar el techo/suelo. Esperar evidencia de que la estructura cambió y después valorar un retest o consolidación.',
    invalidation: 'El supuesto cambio no se sostiene y el precio vuelve a la estructura anterior.',
    mistake: 'Llamar reversión a una sola vela contraria dentro de una tendencia fuerte.',
    level: 'Intermedio',
  },
  {
    title: 'Compresión → expansión',
    context: 'El precio reduce progresivamente su rango y volatilidad antes de un movimiento más amplio.',
    plan: 'Marcar límites de la compresión y esperar confirmación de expansión. El foco está en la gestión, no en predecir el lado de salida.',
    invalidation: 'La salida falla y vuelve al área de compresión.',
    mistake: 'Anticipar una dirección solo porque la figura “parece” alcista o bajista.',
    level: 'Intermedio',
  },
  {
    title: 'Fallo de ruptura',
    context: 'Una ruptura aparente no consigue sostenerse y regresa al rango previo.',
    plan: 'Primero confirmar el fallo; después estudiar si existe espacio razonable hasta la siguiente zona y dónde queda invalidado el escenario.',
    invalidation: 'El precio vuelve a aceptar fuera del rango en la dirección original de la ruptura.',
    mistake: 'Convertir automáticamente todo falso breakout en una entrada contraria.',
    level: 'Avanzado',
  },
]

export const books = [
  {
    title: 'Trading in the Zone',
    author: 'Mark Douglas',
    focus: 'Psicología, incertidumbre y disciplina',
    takeaway: 'Pensar en probabilidades, aceptar que una sola operación no demuestra nada y separar la calidad del proceso del resultado puntual.',
    rating: '4.31/5',
    ratingSource: 'Goodreads · 10k+ valoraciones',
    tag: 'Mentalidad',
  },
  {
    title: 'Japanese Candlestick Charting Techniques',
    author: 'Steve Nison',
    focus: 'Velas, contexto y lectura visual del precio',
    takeaway: 'Las velas ganan sentido cuando se combinan con tendencia, zonas y contexto; una figura aislada no debería tratarse como certeza.',
    rating: '4.7/5',
    ratingSource: 'Amazon · 1k+ valoraciones (referencia consultada)',
    tag: 'Price action',
  },
  {
    title: 'Technical Analysis of the Financial Markets',
    author: 'John J. Murphy',
    focus: 'Estructura, tendencias, soporte/resistencia e indicadores',
    takeaway: 'Construir primero una lectura ordenada del mercado: tendencia, estructura, zonas y confirmaciones, antes de obsesionarse con indicadores.',
    rating: '4.7/5',
    ratingSource: 'Amazon · referencia de reseñas consultada',
    tag: 'Base técnica',
  },
  {
    title: 'Market Wizards',
    author: 'Jack D. Schwager',
    focus: 'Procesos de traders profesionales',
    takeaway: 'No existe un único estilo ganador; se repiten disciplina, control de pérdidas, adaptación y conocimiento profundo del propio método.',
    rating: '4.7/5',
    ratingSource: 'Amazon · 2k+ valoraciones (referencia consultada)',
    tag: 'Experiencia',
  },
  {
    title: 'The New Trading for a Living',
    author: 'Alexander Elder',
    focus: 'Psicología, sistemas, riesgo y diario',
    takeaway: 'Tratar el trading como un proceso medible: plan, riesgo limitado, registro de operaciones y revisión posterior.',
    rating: '4.33/5',
    ratingSource: 'Goodreads · 1.4k+ valoraciones',
    tag: 'Gestión',
  },
]

export const tips = [
  'Antes de tocar BUY o SELL, deberías poder decir en una frase qué tendría que pasar para admitir que tu idea era incorrecta.',
  'El timeframe no hace una señal “mejor”; cambia el nivel de detalle y el horizonte que estás observando.',
  'No confundas una operación ganadora con una buena decisión ni una pérdida con una mala decisión. Evalúa si seguiste tu plan.',
  'Una vela grande después de un movimiento extendido puede ser continuación, agotamiento o ruido. Sin contexto no significa suficiente.',
  'Si necesitas mover el Stop Loss cada vez que el precio se acerca, probablemente tu invalidación no estaba definida antes de entrar.',
  'El spread y el slippage importan más durante volatilidad fuerte, noticias y cambios de liquidez.',
  'Reducir el tamaño de la posición es una herramienta de riesgo; ampliar el stop sin criterio solo aumenta la pérdida potencial.',
  'Lleva un diario: captura del gráfico, razón de entrada, invalidación, resultado y si respetaste el plan.',
  'No necesitas estar siempre dentro del mercado. “No hay operación” también puede ser una decisión válida.',
  'Aprende un setup a profundidad antes de coleccionar veinte patrones distintos.',
]
